import { Get, Post, Body, Put, Delete, Param, Query, Controller, HttpCode,ParseIntPipe, ParseBoolPipe, UsePipes } from '@nestjs/common';
import { ApiBearerAuth, ApiOperation, ApiResponse, ApiTags, ApiParam, ApiBody } from '@nestjs/swagger';
import { AccountCreateDto } from '../dtos/account-create.dto';
import { AccountUpdateDto } from '../dtos/account-update.dto';
import { AccountDto } from '../dtos/account.dto';
import { AccountEntity, CreateAccountProps } from '../entities/account.entity';
import { AccountService } from '../services/account.service';
import { AccountDtoMapper } from '../utils/account-dto.mapper';


@ApiBearerAuth()
@ApiTags('wallet/accounts')
@Controller('wallet/accounts')
export class AccountController { 

  constructor(private readonly accountService: AccountService) {}

  @ApiOperation({ summary: 'Create account' })
  @ApiResponse({ status: 201, description: 'The account has been successfully created.' })
  @ApiResponse({ status: 400, description: 'Invalid input.' })
  @Post()
  async create(@Body(/*new ValidationPipe(VALIDATION_SCHEMA_GAMING_LOUNGE_CREATE)*/) accountCreateDto: AccountCreateDto): Promise<AccountDto> {
    let createPros:CreateAccountProps = AccountDtoMapper.toCreateAccountProps(accountCreateDto);
    let gl:AccountEntity = await this.accountService.create(createPros);
    let glDto:AccountDto = AccountDtoMapper.toAccountDto(gl);
    return glDto;
  }

  @ApiOperation({ summary: 'Update account' })
  @ApiResponse({ status: 200, description: 'The account has been successfully updated.' })
  @ApiResponse({ status: 400, description: 'Invalid uid.' })
  @ApiResponse({ status: 404, description: 'Account not found by the given uid.' })
  @Put(':uid')
  async update(@Param('uid') uid: string,@Body(/*new ValidationPipe(VALIDATION_SCHEMA_GAMING_LOUNGE_UPDATE)*/) accountUpdateDto: AccountUpdateDto) {
    let updatePros:CreateAccountProps = AccountDtoMapper.toUpdateAccountProps(uid,accountUpdateDto);
    let gl:AccountEntity = await this.accountService.update(uid,updatePros);
    let glDto:AccountDto = AccountDtoMapper.toAccountDto(gl);
    return glDto;
  }

  @ApiOperation({ summary: 'Find all accounts' })
  @ApiResponse({ status: 200, description: 'Return all accounts.'})
  @Get('')
  async findAll(): Promise<AccountDto[]> {
    let gls:AccountEntity[] = await this.accountService.findAll(null,null);
    let glDtos:AccountDto[] = AccountDtoMapper.toAccountDtos(gls);
    return glDtos;
  }

  @ApiOperation({ summary: 'Find all accounts by the given query string params.' })  
  @ApiResponse({ status: 200, description: 'Return all accounts found.'})
  @Get('filter')
  async findByQueryParam(@Query('desc') desc: string,@Query('deleted',ParseBoolPipe) deleted: boolean): Promise<AccountDto[]> {
    let gls:AccountEntity[] = await this.accountService.findAll(null,null);
    let glDtos:AccountDto[] = AccountDtoMapper.toAccountDtos(gls);
    return glDtos;
  }

  @ApiOperation({ summary: 'Find a account by the given uid.' })
  @ApiParam({ name: "uid", description: "Unique account uid generated by the system for the account entities.", required: true, allowEmptyValue: false })
  @ApiResponse({ status: 200, description: 'Return account found by the given uid.'})
  @ApiResponse({ status: 400, description: 'Invalid uid.' })
  @ApiResponse({ status: 404, description: 'Account not found by the given uid.' })
  @Get(':uid')
  async findById(@Param('uid') uid: string): Promise<AccountDto> {
    
    let gl:AccountEntity = await this.accountService.findById(uid);
    let glDto:AccountDto = AccountDtoMapper.toAccountDto(gl);

    return glDto;
  }

  @HttpCode(204)
  @ApiOperation({ summary: 'Delete a account by the geiven uid' })
  @ApiResponse({ status: 204, description: 'The account has been successfully deleted.'})
  @ApiResponse({ status: 400, description: 'Invalid uid.' })
  @ApiResponse({ status: 404, description: 'Account not found by the given uid.' })
  @Delete(':uid')
  async delete(@Param('uid') uid: string): Promise<void> {
    await this.accountService.delete(uid);

  }

  @HttpCode(204)
  @ApiOperation({ summary: 'Purge account' })
  @ApiResponse({ status: 204, description: 'The account has been successfully purged.'})
  @ApiResponse({ status: 400, description: 'Invalid uid.' })
  @ApiResponse({ status: 404, description: 'Account not found by the given uid.' })
  @Delete('purge/:uid')
  async purge(@Param('uid') uid: string): Promise<void> {
    await this.accountService.delete(uid);
  }
}